#开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentinformation
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#配置mybatis参数
mybatis:
  #type-aliases-package中指定entity扫描包类让mybatis自定扫描到自定义的entity
  type-aliases-package: com.qin.boot.entity
  mapper-locations: classpath:mapper/*.xml
